### ISSUE TITLE
Automate restoring accidentally deleted migration files

### ISSUE THREAD

**Issue by raddevon** [edgedb/edgedb-cli#1115] opened 2023-08-28 14:03 UTC
It feels like this has the right combination of frequency of occurrence, relative ease to implement, and difficulty for users to do themselves to justify adding it to the CLI.

I just tried to explain how to do it to a Discord user and landed on this:

>  ```
> select schema::Migration {
>   name,
>   script,
>   parents: {name}
> }
> ```
> 
> You could rebuild them from that, either manually or via a script. Migrations are named sequentially starting from 00001.edgeql.
> 
> Files are in this format:
> ```
> CREATE MIGRATION <name>
>     ONTO <parent.name> # or `initial` if this is the first migration
> {
>   <script>
> };
> ```
>
> The first migration is the one with nothing linked on parents, and the others proceed from there by chaining the links (i.e., the Migration with the first migration linked in parents is the second migration — 00002.edgeql — and so on).

Not sure if that's all 100% correct and "the right way"™, but, if it is at least close, I feel it could be worth implementing.

**Comment by elprans** [comment] 2023-08-28 16:14
Dupe of #270

**Closed by elprans** 2023-08-28 16:14 UTC
