### ISSUE TITLE
Getting into CLI after setting `force_database_error`?

### ISSUE THREAD

**Issue by jackfischer** [edgedb/edgedb-cli#1321] opened 2024-05-08 15:55 UTC
- EdgeDB Version: 4.7
- EdgeDB CLI Version: 5.1.0
- OS Version: macos

Steps to Reproduce:

1. Set `force_database_error`, eg `configure current database set force_database_error := '{"type": "QueryError", "message": "ongoing maintenance"}';`
2. If you quit your CLI session, you are seemingly permanently locked out and can't run `configure current database reset force_database_error;`:

```sh
$ edgedb
EdgeDB 4.7+45e4acc (repl 5.1.0+8ff9f85)
edgedb error: ConfigurationError: invalid 'force_database_error' value'
```

Luckily was able to get in via the UI.

**Comment by msullivan** [comment] 2024-05-08 16:28
Whoops, I actually had this issue half-filed in a tab from last Friday and never submitted.

I am pretty certain this is a regression, because I remember checking that this worked when I first suggested `force_database_error` to you.

```
edgedb query 'configure current database reset force_database_error;'
```
will still work

**Comment by jackfischer** [comment] 2024-05-08 18:39
Ah, forgot about that non-REPL option. Thanks

**Comment by msullivan** [comment] 2024-05-08 20:24
(The fix for this should also include a test in `tests/func/interactive.rs`)

**Closed** 2024-05-10 15:26 UTC
Labels: bug, high-priority
