### ISSUE TITLE
Can't initialize project with previous version

### ISSUE THREAD

**Issue by internalfx** [edgedb/edgedb-cli#687] opened 2022-03-22 22:25 UTC
- EdgeDB Version: 1.2
- OS Version: pop_os 21.10

Steps to Reproduce:

`:$ edgedb project init --server-version=1.1`

```
Checking EdgeDB versions...
┌────────────────────────┬──────────────────────────────────────────────────────────────┐
│ Project directory      │ /home/XXXXXXXXXXXXX/projects/test             │
│ Project config         │ /home/XXXXXXXXXXXXX/projects/test/edgedb.toml │
│ Schema dir (non-empty) │ /home/XXXXXXXXXXXXX/projects/test/dbschema    │
│ Installation method    │ portable package                                             │
│ Start configuration    │ manual                                                       │
│ Version                │ 1.2+5aecabc                                                  │
│ Instance name          │ test                                               │
└────────────────────────┴──────────────────────────────────────────────────────────────┘
```

I also tried the following just to be sure:
`edgedb project init --server-version 1.1`
`edgedb project init --server-version "1.1"`

**Comment by tailhook** [comment] 2022-03-28 12:42
I'm not sure this is the bug. The `--server-version=1.1` means `^1.1` by semver. Which is essentially `>=1.1.0 AND <2.0.0`. There is a precedent of treating versions as such at least in `Cargo.toml`.

Generally we expect that you never need to install older minor version. What is your use case?

**Comment by internalfx** [comment] 2022-03-28 14:58
> Generally we expect that you never need to install older minor version.

Only can be possibly true if you think your team will never now or in the future produce any regressions in your software.

> What is your use case?

I was trying to track down a bug and wanted to eliminate the version of edgeDB I was using because I had recently upgraded when the bug occurred.

I had (naively) assumed that the version rules worked similarly to NPM.

So then is it impossible to request a specific version of the software? If so, that seem like an unfortunate (and probably unnecessary) limitation.

What happens if I'm doing development and my `edgedb.toml` specifies 1.1 and I haven't upgraded in a while? Do I then end up deploying 1.2 or something later? Because the server will not respect my 1.1 specification? This seems like a risky design decision from my view.

However, I'm really enjoying what your team has produced so far.

**Comment by tailhook** [comment] 2022-03-29 19:15
> > Generally we expect that you never need to install older minor version.
> 
> Only can be possibly true if you think your team will never now or in the future produce any regressions in your software.
> 

Well, it's not as easy. While yes, we expect to produce no regressions it's hard to get that in 100% cases.

But the problem is that it's more likely users will have bugs due to not updating their version in time than because we had a regression (which we expect to fix quickly).

Note `1.x` is a no-feature, bugfix release in our versioning.

So at least default must be caret-version. We might add some `=1.1` or `--exact` flag in future, but not use that by default.

> > What is your use case?
> 
> I was trying to track down a bug and wanted to eliminate the version of edgeDB I was using because I had recently upgraded when the bug occurred.
> 
> I had (naively) assumed that the version rules worked similarly to NPM.
> 
> So then is it impossible to request a specific version of the software? If so, that seem like an unfortunate (and probably unnecessary) limitation.
> 
> What happens if I'm doing development and my `edgedb.toml` specifies 1.1 and I haven't upgraded in a while? Do I then end up deploying 1.2 or something later? Because the server will not respect my 1.1 specification? This seems like a risky design decision from my view.
> 

Node uses caret version by default if you use `npm install --save` so this is very similar (even if notation is a bit different). Like I've said this notation is used in another mainstream package manager "cargo".

Also, note that EdgeDB versions are not semver. We only introduce features in major versions and use minor (second component) for patch/bugfix releases. So yes, if you used `1.1` for a while and then checkout project and it installs `1.9` or similar, everything is expected to work.

**Comment by internalfx** [comment] 2022-03-29 19:42
> But the problem is that it's more likely users will have bugs due to not updating their version in time than because we had a regression (which we expect to fix quickly).

Your users are more than likely professional software engineers themselves, I wouldn't recommend thinking _for_ them about when they should update their software.

> Node uses caret version by default if you use npm install --save so this is very similar (even if notation is a bit different). Like I've said this notation is used in another mainstream package manager "cargo".

The notation is the critical difference in my opinion. Yes, npm does add a caret by default, but it's an actual caret in the package.json file that you can see and delete. If you remove the caret than it will give you the exact version you ask for. So it's easy to visually verify what "strictness" you will get from npm, and override it if necessary.

> We might add some =1.1 or --exact flag in future, but not use that by default.

I'm not too picky about how it works, but I think there should be a way.

**Comment by tailhook** [comment] 2022-05-27 10:42
Duplicate of #686

**Closed by tailhook** 2022-05-27 10:42 UTC
Labels: enhancement
