### ISSUE TITLE
invlid bytes literal seems to break the repl

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb-cli#307] opened 2021-04-23 23:00 UTC
- EdgeDB Version: EdgeDB 1.0-beta.1+g2eee1afe4.d20210301
- EdgeDB CLI Version: repl 1.0.0-beta.1
- OS Version: Linux 5.11.0-14-generic #15-Ubuntu SMP Thu Apr 8 21:39:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

If you type the query `SELECT b'\';` in the repl a couple of things happen.
1. the syntax highlighting for the byte literal goes away.
2. hitting `<CR>` after the semicolon doesn't run the query.

These behaviors seem like they would cause useres to:
1. think the repl is broken
2. not get feed back that their bytes literal is not valid.

Perhaps the query should be submitted so that the user can learn from the error message? It also seems like the highlighting should still work even though the bytes literal is not valid. 

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/8278635/115937188-1e6f1c00-a44c-11eb-94a7-a2d920adfe4f.png)

**Comment by Fogapod** [comment] 2021-04-24 18:29
I think the only issue here is partial string not being highlighted (both normal strings and strings with prefix).

In your example you didn't close `'`, after entering closing quote repl correctly parses newlines.

The solution could be highlighting open quote and `.......` with string color when multiline string is being entered.

**Comment by tailhook** [comment] 2021-04-26 12:43
Yes, this is not a bug. We allow multiline-strings:
```
edgedb> SELECT b'line1
........ line2';
```
And we allow escaping apostrophes:
```
edgedb> SELECT b'don\'t hesitate'; 
```

And no, we don't highlight partial tokens yet. It's probably hard to do in general case.

**Closed by tailhook** 2021-04-26 12:43 UTC
