### ISSUE TITLE
`edgedb instance link` interactive prompts do not default to values already provided in the DSN

### ISSUE THREAD

**Issue by raddevon** [edgedb/edgedb-cli#937] opened 2023-02-08 17:09 UTC
- EdgeDB Version: 2.9+4fbadd2
- EdgeDB CLI Version: 2.3.0-dev.907+7c84a91
- OS Version: macOS Ventura 13.0.1

Steps to Reproduce:

1. Link to an instance using `edgedb instance link <name> --dsn edgedb://edgedb:<password>@localhost:10762/<db-name>`
2. Answer host, port, and database user prompts
3. Observe that the database name prompt does not reflect the database name in the DSN provided to the CLI

I expected this to either not prompt for any data already included in the DSN or for the default input to mirror the one included in the DSN.

This also prompts for the password even though it is already included in the DSN. Is that required?

**Comment by tailhook** [comment] 2023-02-24 15:39
Duplicate of #844

**Closed by tailhook** 2023-02-24 15:39 UTC
