### ISSUE TITLE
`edgedb project init --link` should not require `edgedb.toml`

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb-cli#841] opened 2022-09-20 21:07 UTC
There is no reason why initializing a new project with a remote instance shouldn't be supported.  `--link` should query the remote instance for the server version and write it into `edgedb.toml`.

**Comment by tailhook** [comment] 2023-05-23 14:08
Duplicate of #497

**Closed by tailhook** 2023-05-23 14:08 UTC
