### ISSUE TITLE
Remove usage of deprecated `--echo-runtime-info`

### ISSUE THREAD

**Issue by fantix** [edgedb/edgedb-cli#385] opened 2021-07-17 12:48 UTC
`edgedb-server --echo-runtime-info` is deprecated, CLI should use the new `--emit-server-status` option in tests.

**Comment by 1st1** [comment] 2021-08-23 18:04
duplicate of https://github.com/edgedb/edgedb-cli/issues/479

**Closed by 1st1** 2021-08-23 18:04 UTC
