### ISSUE TITLE
Panic when migrating on a cloud instance

### ISSUE THREAD

**Issue by aljazerzen** [edgedb/edgedb-cli#1078] opened 2023-06-13 12:28 UTC
```
➜  EdgeDB edgedb project init --server-instance aljazerzen/time-tracker-edge
[2023-06-13T12:26:17Z WARN  edgedb::version_check] Newer version of edgedb tool exists 3.1.3+9e580f2 (current 3.1.0+69bd230). To upgrade run `edgedb cli upgrade`
No `edgedb.toml` found in `/home/aljaz/EdgeDB` or above
Do you want to initialize a new project? [Y/n]
> YY
edgedb error: Please answer Y or N
> Y
Specify the name of EdgeDB instance to use with this project [default: aljazerzen/time-tracker-edge]:
> aljazerzen/time-tracker-edge
Do you want to use existing instance "aljazerzen/time-tracker-edge" for the project? [y/n]
> y
Applying migrations...
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/migrations/migrate.rs:214:41
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

- EdgeDB Version: 3.0-rc1
- EdgeDB CLI Version: 3.1.0+69bd230
- OS Version: Linux

**Comment by tailhook** [comment] 2023-06-13 13:05
Duplicate of #1076. Fixed in #1077

**Closed** 2023-06-13 14:52 UTC
Labels: bug
