### ISSUE TITLE
Limit max table width

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-cli#21] opened 2020-03-31 01:29 UTC
We should do word-wrapping for overly long lines to makes sure tables are rendered nicely.

![Screen Shot 2020-03-30 at 6 29 04 PM](https://user-images.githubusercontent.com/239003/77977377-69077e80-72b4-11ea-81bd-6d312b115f9a.png)

**Comment by tailhook** [comment] 2020-03-31 08:59
Duplicate of #13

**Closed by tailhook** 2020-03-31 08:59 UTC
