### ISSUE TITLE
union types should be hidden from `\lt`

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-cli#180] opened 2020-10-23 06:29 UTC
There's no point in showing union types in `\lt` since they're autogenerated by the system and there's little to no utility in introspecting them for the user:

```
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────┐
│                                                             Name                                                              │                                  Extending                                   │
├───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────────────────────────────────────────────────────────────────┤
│ default::(f0eb319c-0ced-11eb-b319-87959ea7db92 | f13aa862-0ced-11eb-ba00-9ff8e77e01d9)                                        │ std::BaseObject                                                              │
│ default::(f17aac8c-0ced-11eb-8b3f-bb4972c7a63b | f17fc3de-0ced-11eb-a566-279b924a7c8e | f1aaea96-0ced-11eb-9a60-c7420c4419e8) │ std::BaseObject                                                              │
│ default::A                                                                                                                    │ std::BaseObject, std::Object
```

They do, however, break the table formatting as their names are wide.

**Comment by tailhook** [comment] 2020-10-23 08:55
Duplicate of #169

**Closed by tailhook** 2020-10-23 08:55 UTC
